name: BlackCov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
      - name: Lint
        uses: psf/black@stable
      - name: Generate coverage report
        run: |
          conda install -c conda-forge cartopy
          pip install Cython
          pip install pyshp six
          pip install six
          pip install pytest
          pip install pytest-cov
          pip install numpy
          pip install pandas
          pip install matplotlib
          pip install holoviews
          pip install palettable
          pip install geopandas
          pip install mapclassify
          pip install seaborn
          pip install cmasher
          pip install geoviews
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
